// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0
// source: poke_orders.sql

package db

import (
	"context"
)

const cancelPokemonOrderData = `-- name: CancelPokemonOrderData :one
DELETE FROM poke_orders
WHERE id = $1
RETURNING product_id
`

func (q *Queries) CancelPokemonOrderData(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRowContext(ctx, cancelPokemonOrderData, id)
	var product_id int64
	err := row.Scan(&product_id)
	return product_id, err
}

const insertPokemonOrderData = `-- name: InsertPokemonOrderData :one
INSERT INTO poke_orders (
    user_id, product_id,quantity,total_price,order_detail
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, product_id, quantity, total_price, order_detail, created_at
`

type InsertPokemonOrderDataParams struct {
	UserID      int64  `json:"user_id"`
	ProductID   int64  `json:"product_id"`
	Quantity    int32  `json:"quantity"`
	TotalPrice  int64  `json:"total_price"`
	OrderDetail string `json:"order_detail"`
}

func (q *Queries) InsertPokemonOrderData(ctx context.Context, arg InsertPokemonOrderDataParams) (PokeOrder, error) {
	row := q.db.QueryRowContext(ctx, insertPokemonOrderData,
		arg.UserID,
		arg.ProductID,
		arg.Quantity,
		arg.TotalPrice,
		arg.OrderDetail,
	)
	var i PokeOrder
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.ProductID,
		&i.Quantity,
		&i.TotalPrice,
		&i.OrderDetail,
		&i.CreatedAt,
	)
	return i, err
}

const listPokemonOrderData = `-- name: ListPokemonOrderData :many
SELECT id, user_id, product_id, quantity, total_price, order_detail, created_at FROM poke_orders
WHERE 
    user_id = $1 OR
    product_id = $2
ORDER BY id
LIMIT $3
OFFSET $4
`

type ListPokemonOrderDataParams struct {
	UserID    int64 `json:"user_id"`
	ProductID int64 `json:"product_id"`
	Limit     int32 `json:"limit"`
	Offset    int32 `json:"offset"`
}

func (q *Queries) ListPokemonOrderData(ctx context.Context, arg ListPokemonOrderDataParams) ([]PokeOrder, error) {
	rows, err := q.db.QueryContext(ctx, listPokemonOrderData,
		arg.UserID,
		arg.ProductID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PokeOrder
	for rows.Next() {
		var i PokeOrder
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.ProductID,
			&i.Quantity,
			&i.TotalPrice,
			&i.OrderDetail,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
