// Code generated by sqlc. DO NOT EDIT.

package db

import (
	"context"
)

type Querier interface {
	AddPokemonStockData(ctx context.Context, arg AddPokemonStockDataParams) (PokeProduct, error)
	CancelPokemonOrderData(ctx context.Context, id int64) error
	CreateAccountLog(ctx context.Context, arg CreateAccountLogParams) (Account, error)
	CreatePokemonData(ctx context.Context, arg CreatePokemonDataParams) (PokeProduct, error)
	CreateUserAccount(ctx context.Context, arg CreateUserAccountParams) (User, error)
	DeductPokemonStockData(ctx context.Context, arg DeductPokemonStockDataParams) (PokeProduct, error)
	DeleteUserAccount(ctx context.Context, id int64) error
	GetAccountLog(ctx context.Context, username string) (Account, error)
	GetPokemonData(ctx context.Context, id int64) (PokeProduct, error)
	GetPokemonOrderData(ctx context.Context, id int64) (PokeOrder, error)
	GetUserAccount(ctx context.Context, id int64) (User, error)
	InsertPokemonOrderData(ctx context.Context, arg InsertPokemonOrderDataParams) (PokeOrder, error)
	ListOrderDetailedData(ctx context.Context, arg ListOrderDetailedDataParams) ([]ListOrderDetailedDataRow, error)
	ListPokemonData(ctx context.Context, arg ListPokemonDataParams) ([]PokeProduct, error)
	ListPokemonOrderData(ctx context.Context, arg ListPokemonOrderDataParams) ([]PokeOrder, error)
	ListUserAccount(ctx context.Context, arg ListUserAccountParams) ([]User, error)
	UpdatePokemonData(ctx context.Context, arg UpdatePokemonDataParams) (PokeProduct, error)
	UpdateUserAccountRole(ctx context.Context, arg UpdateUserAccountRoleParams) (User, error)
}

var _ Querier = (*Queries)(nil)
